### ISSUE TITLE
Error While deploying app on Device

### ISSUE THREAD

**Issue by rajsanil** [Microsoft/TailwindTraders-Mobile#11]
Unhandled Exception:  Java.Lang.NoSuchMethodError: <Timeout exceeded getting exception details> occurred

**Comment by MarcosCobena** [comment]
Hi @rajsanil,

Thanks for giving a try to the repo :-)

Could you please send us some more information: stack trace, env set-up, things like that?

In advance, it looks for me you're using an older version of the Android SDK (build tools and so on), could you please double-check it and if applies try updating them?

—Marcos

**Comment by MarcosCobena** [comment]
Let me please close this issue for now, feel free to reopen it if may be needed again.
