### ISSUE TITLE
does shell work on Xamarin.mac & UWP- this example doesn't have Xamarin.mac or UWP example

### ISSUE THREAD

**Issue by ghost** [Microsoft/TailwindTraders-Mobile#20]
does shell work on Xamarin.mac & UWP- this example doesn't have Xamarin.mac or UWP example

**Comment by MarcosCobena** [comment]
As it's currently stated in the official documentation

https://docs.microsoft.com/es-es/xamarin/xamarin-forms/app-fundamentals/shell

Android & iOS seem to be the ones supported.
