### ISSUE TITLE
Android Build fails - errors XA2002 and APT0000

### ISSUE THREAD

**Issue by francis2** [Microsoft/TailwindTraders-Mobile#21]
Running on Windows 10 x64 with VS2019 preview 2.1. I downloaded twice and built many times, also tried to place files in a different folder.

1>------ Build started: Project: Emgu.TF.Lite, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.600-preview-009472\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
1>Emgu.TF.Lite -> C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\ThirdParties\Emgu.TF.Lite\bin\Debug\netstandard1.1\Emgu.TF.Lite.dll
2>------ Build started: Project: TailwindTraders.Mobile, Configuration: Debug Any CPU ------
2>TailwindTraders.Mobile -> C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile\bin\Debug\netstandard2.0\TailwindTraders.Mobile.dll
3>------ Build started: Project: TailwindTraders.Mobile.Android, Configuration: Debug Any CPU ------
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'colorAccent'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'buttonStyle'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorAccent'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimary'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionBar'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionModeOverlay'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowNoTitle'.
3>C:\TailwindTraders-Mobile-develop\TailwindTraders-Mobile-develop\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1925,2): error XA2002: Can not resolve reference: `Xamarin.Forms.Core`, referenced by `TailwindTraders.Mobile.Android`. Please add a NuGet package or assembly reference for `Xamarin.Forms.Core`, or remove the reference to `TailwindTraders.Mobile.Android`.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1925,2): error XA2002: Can not resolve reference: `Xamarin.Forms.Core`, referenced by `Sharpnado.Presentation.Forms`. Please add a NuGet package or assembly reference for `Xamarin.Forms.Core`, or remove the reference to `Sharpnado.Presentation.Forms`.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1925,2): error XA2002: Can not resolve reference: `Xamarin.Forms.Core`, referenced by `Sharpnado.Presentation.Forms.Droid`. Please add a NuGet package or assembly reference for `Xamarin.Forms.Core`, or remove the reference to `Sharpnado.Presentation.Forms.Droid`.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1925,2): error XA2002: Can not resolve reference: `Xamarin.Forms.Xaml`, referenced by `TailwindTraders.Mobile`. Please add a NuGet package or assembly reference for `Xamarin.Forms.Xaml`, or remove the reference to `TailwindTraders.Mobile`.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by francis2** [comment]
Tried on 2 different computers. Same result.

**Comment by MarcosCobena** [comment]
Hi @francis2,

The only difference I see between your env and ours is VS 2019: we're using 2017 on Windows and VS for Mac stable under macOS, and just works on both. Could you please try with some other stable bits?

Thanks,

—Marcos

**Comment by francis2** [comment]
Hi Marco, thanks for looking into this. I downloaded the demo again today with your update, but it still fails on both versions of VS.

Result in VS 2017 15.9.6
1>------ Rebuild All started: Project: Emgu.TF.Lite, Configuration: Debug Any CPU ------
1>Emgu.TF.Lite -> C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\ThirdParties\Emgu.TF.Lite\bin\Debug\netstandard1.1\Emgu.TF.Lite.dll
2>------ Rebuild All started: Project: TailwindTraders.Mobile, Configuration: Debug Any CPU ------
2>TailwindTraders.Mobile -> C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile\bin\Debug\netstandard2.0\TailwindTraders.Mobile.dll
3>------ Rebuild All started: Project: TailwindTraders.Mobile.Android, Configuration: Debug Any CPU ------
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: No resource found that matches the given name: attr 'colorAccent'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'buttonStyle'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorAccent'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimary'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionBar'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionModeOverlay'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'windowNoTitle'.
3>C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile.Android\Resources\values\themes.xml(2): error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

--------------------------------------------------------------------------
Result in VS2019 2.1
1>------ Rebuild All started: Project: Emgu.TF.Lite, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.600-preview-009472\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
1>Emgu.TF.Lite -> C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\ThirdParties\Emgu.TF.Lite\bin\Debug\netstandard1.1\Emgu.TF.Lite.dll
2>------ Rebuild All started: Project: TailwindTraders.Mobile, Configuration: Debug Any CPU ------
2>TailwindTraders.Mobile -> C:\TailwindTraders-Mobile-master\Source\TailwindTraders.Mobile\TailwindTraders.Mobile\bin\Debug\netstandard2.0\TailwindTraders.Mobile.dll
3>------ Rebuild All started: Project: TailwindTraders.Mobile.Android, Configuration: Debug Any CPU ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error XA0115: Invalid value 'armeabi' in $(AndroidSupportedAbis). This ABI is no longer supported. Please update your project properties.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

**Comment by francis2** [comment]
I was able to fix the project and it now compiles in both versions of VS. 

Go in Android solution properties->Android Options->Advanced->uncheck armebi, then check it again.

**Comment by MarcosCobena** [comment]
Oh, nice to know; would it be possible you share which changes were made after toggling that? Thanks anyway, let me close this issue, feel free to write below anyway.

**Comment by francis2** [comment]
I made no other change: it looks like VS2019 does not support armeabi (but V7 is supported).

![image](https://user-images.githubusercontent.com/11061648/52221992-7a035e00-2870-11e9-8c5f-d64f9c35e98b.png)

**Comment by MarcosCobena** [comment]
OK, thanks anyway :-)

**Comment by jerryno6** [comment]
Thanks, I just need to remove armebi in Andoird project. Then rebuilt it. The error vanished after that :)
You should keep the armeabi-v7a to make it work on real devices
![Screen Shot 2019-04-10 at 10 44 33](https://user-images.githubusercontent.com/4426269/55850338-21a55100-5b7e-11e9-91d5-bca137b7ec29.png)

**Comment by pulimento** [comment]
Good to know, thanks! :)
