### ISSUE TITLE
appcenter test.

### ISSUE THREAD

**Issue by junpark12** [Microsoft/TailwindTraders-Mobile#28]
Hi I followed instruction at https://www.azuredevopslabs.com/labs/vstsextend/appcenter/.
It worked well.
I have a question about appcenter test.
When i build the app in appcenter, it automated device test as well.
When i see the test result, it only has single result which is "app does launch".
![image](https://user-images.githubusercontent.com/20918194/53790121-8959f200-3f69-11e9-8f0d-aa532805fe02.png)

I downloaded source code and ran unit test. It has several test like login, common.. etc..

![image](https://user-images.githubusercontent.com/20918194/53790406-36cd0580-3f6a-11e9-8397-48fdfce0276c.png)

How can i run the same unit test in app center other than simple app launch?
Thanks.

**Comment by junpark12** [comment]
When i access appcenter test log, i found out following logs.
This might be related to test result?

com.microsoft.appcenter.http.HttpException: 401 - CorrelationId: bd47441b-e7d6-4bdb-8b99-1cc3ab2b52df  ReasonCode: AppSecretDenied   at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java: 282)  at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java: 296)  at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java: 39)  at android.os.AsyncTask$2.call(AsyncTask.java: 333)  at java.util.concurrent.FutureTask.run(FutureTask.java: 266)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java: 1167)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java: 641)  at java.lang.Thread.run(Thread.java: 764)

**Comment by pulimento** [comment]
Hello! Thanks for trying our sample.

You are having this error because you need to set some environment variables in AppCenter. Please, read the instructions [here](https://github.com/Microsoft/TailwindTraders-Mobile/blob/master/Source/TailwindTraders.Mobile/TailwindTraders.Mobile.Android/appcenter-post-build.sh#L11)

Don't hesitate to come here if you continue with problems.

**Comment by dsanchezcr** [comment]
Closing the issue since the solution was provided.
