### ISSUE TITLE
Question: Why not MVVM frameworks?

### ISSUE THREAD

**Issue by tibitoth** [Microsoft/TailwindTraders-Mobile#3]
Just for my curiosity why do not you Prism library or ReactiveUI for MVVM functionality?

**Comment by davidortinau** [comment]
No particular reason other than to focus on the fundamentals of using Xamarin.Forms itself instead of introducing additional concepts. Those are both great libraries. 

What would you like to see in our next reference app? What would you hope to learn from it?

**Comment by learn9969** [comment]
Hi 
you guys are doing an amazing job with xamarin forms!!! 

xmas list:)
I would like to see a reference app using PrismLib  (best framework)

- that  uses  AzureDevops  to build it and in the release pipeline distribute via appcenter (real world)
- usage of css allover 
- usage of collectionview
- and   the most important feature of them all that you guys allow us todo  livereload 

We waste HOURS launching the app all the time to see if it looks how we want it

Many thanks

**Comment by luismts** [comment]
@davidortinau is there a way that I can participate in doing this kind of example, contributing or something else in this kind of initiative?

**Comment by Predatorie** [comment]
I love Xamarin and the work you guys put into it but after playing around with Flutter I will say that Hot Reloading is mind blowing, is there anything like this coming for Xamarin? Having to recompile, deploy etc. while testing out a UI is just painful and kills productivity.

**Comment by davidortinau** [comment]
@learn9969 @Predatorie your best options today are http://gorillaplayer.com and https://livexaml.com  for runtime iteration on your UI.

@luismts keeping with the theme of this Issue topic, it sounds like Prism and ReactiveUI versions of this app would be a nice contribution.

**Comment by luismts** [comment]
@davidortinau nice! Let's me see how I can take an space in my schedule to work on it

**Comment by MarcosCobena** [comment]
Let me please close this issue for now, feel free to reopen it if may be needed again.
