### ISSUE TITLE
Nice Demo but too complex

### ISSUE THREAD

**Issue by markti** [Microsoft/TailwindTraders-Mobile#45]
can you make a simpler solution that doesn't have all features? maybe only the basic navigation and authentication?

**Comment by pulimento** [comment]
Hi @markti, glad you liked our demo!

For a simpler demo app, you can take a look at [AIVisualProvision App](https://github.com/Microsoft/AIVisualProvision/). That app has implemented a navigation service, and has less screens and less UI complexity than TailWind Traders has.

If you want further little demos, you can follow to [David Ortinau](https://github.com/davidortinau), [James Montemagno](https://github.com/jamesmontemagno) or [Javier Suarez](https://github.com/jsuarezruiz) GitHub accounts (amongst other, these are the first that came to my mind).

Have a nice day!

**Comment by pulimento** [comment]
If you want more info about implementing authentication in your app, our recommendation is to use the recent Microsoft authentication libraries, take a look at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries

**Comment by markti** [comment]
@pulimento Thanks for the response, I looked at AIVisualProvision but it doesnt have all the nice Xamarin shell / Feature structure / Framework. That's the part of the demo i'm interested in. I'm in the process of re-creating a simpler version of this with only the following features: LogOn, Shell, Home, Settings. I have a very sophisticated WebAPI so the backend is all set I'm just trying to figure out how to do Xamarin.Forms the right way...

**Comment by meteorsnows** [comment]
@markti, I can see you really interesting on this topic. You can check [Xamarin 4 References app in this link](https://devblogs.microsoft.com/xamarin/introducing-xamarin-forms-4-0-the-era-of-shell/?fbclid=IwAR0XBqW7YD4MQMBhrlYe9TXrmo1YGZjmfb46xsrherw5uH52g4n4apVTBkE)

I am also kinda quite interested on how Xamarin worked cross platform over UWP/iOS/Apple and even Mac OS X, but Microsoft team pushed more on MS Edge Chromium to Mac OS X recently. 

Comparison to other framework, Xamarin consider quite hard to entry, as the community is smaller. But I still feel it might be better than UWP for a bit. But UWP gonna easier to picked up.

**Comment by pulimento** [comment]
@meteorsnows honestly, I don't feel that the Xamarin community is that smaller. It's David Ortinau, James Montemagno, Javier Suárez, and many mary more in the scene. Probably following in twitter the right profiles, you can get all the support you want.

@markti We've added some shell features recently, including route-based navigation, if you're interested
