### ISSUE TITLE
Shell Navigation with custom routing does not work

### ISSUE THREAD

**Issue by markti** [Microsoft/TailwindTraders-Mobile#49]
I'm trying to get navigation to work using Shell and when I navigate using Shell.GoToAsync(string) it does nothing...how do I report this issue or get help with this?

**Comment by pulimento** [comment]
You've just reported it :) Please give us time, and we'll give a look.
Thanks

**Comment by pulimento** [comment]
We'll probably use the Shell navigation with routes feature in this project - no ETA though

**Comment by pulimento** [comment]
BTW, It's done in the 'q2-maintenance' branch 
https://github.com/microsoft/TailwindTraders-Mobile/commit/cf7a4e398200b58505226ca8ca72a58c4e1a2314

Will be eventually merged into 'master'

**Comment by pulimento** [comment]
Update status: It's on a PR just waiting to merge (#62)

**Comment by pulimento** [comment]
Done on master branch. Thanks for the suggestion!
