### ISSUE TITLE
Could not find any available provisioning profiles for iOS

### ISSUE THREAD

**Issue by firelamb** [Microsoft/TailwindTraders-Mobile#58]
OS - MacOS
VS - VS for mac

I get the error:
Could not find any available provisioning profiles for iOS

**Comment by MarcosCobena** [comment]
Hi @firelamb,

iOS is a little bit "tricky" to set up for the first time in terms of signing: if you have never worked with this I'd recommend this guide which can help you sort this out:

https://docs.microsoft.com/es-es/xamarin/ios/get-started/installation/device-provisioning/

Actually, there's no need to pay for a developer account: you can simply rely on your iCloud one and create as much free provisioning profiles as you need:

https://docs.microsoft.com/es-es/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos

I hope both links help you run Tailwind Traders for iOS locally :-) Let me please close this issue for now.

Thanks,

—Marcos
