### ISSUE TITLE
App crashes when taking a photo

### ISSUE THREAD

**Issue by Mikilll94** [Microsoft/TailwindTraders-Mobile#59]
App crashes when taking a photo. Tested on Android. Also the camera movement is very slow and choppy.

**Comment by MarcosCobena** [comment]
Hi @Mikilll94,

Sorry to hear that :-S

I can't see any error log in App Center for the Android app —I see some related to failed API calls however—, may you use the app again a little bit to give some time for the logs to upload? If that wouldn't work, may you share with us the the log cat? You'd need to connect the device through adb.

Thanks for your patience, and sorry again,

—Marcos

**Comment by MarcosCobena** [comment]
Let me please close this issue for now, we always can reopen it if needed.
